### ISSUE TITLE
[Feature request] BIP39 tool

### ISSUE THREAD

**Issue by plavirudar** [LedgerHQ/blue-app-monero#17]
Currently, the Monero Ledger app generates its address and keys from the master key, but the process that this is done is not publicly available and can only be done in the Ledger. 

I would like to request that a tool be made available, similar to [the Iancoleman BIP39 tool](https://iancoleman.io/bip39/) that allows the Monero mnemonic to be derived independently from the Ledger using only the BIP39 master mnemonic.

**Comment by cslashm** [comment]
Done. Will be available in netx released

**Comment by jonathancross** [comment]
@cslashm  Can you please provide a link to the tool?
