### ISSUE TITLE
Support for Ledger Blue?

### ISSUE THREAD

**Issue by franksanders** [LedgerHQ/blue-app-monero#22]
Hi,

I'm trying to install the application on my ledger blue and when following the directions here: 

https://github.com/LedgerHQ/blue-app-monero/blob/master/doc/user/bolos-app-monero.pdf

I am not able to locate the Monero application in either Ledger Manager or Ledger Live with or without developer mode enabled. 

A tweet exhcange with LedgerHQ indicated that this was a community supported app and was not currently supported on the Blue and to contact the developers for further assistance, which doesn't align with what's contained in the documentation.

![image](https://user-images.githubusercontent.com/4338755/44040602-92f33518-9ed0-11e8-8777-6982d8680595.png)

Is the app currently support on the blue? If so I would appreciate any help in getting the application loaded. If not, I'm logging interest in support. 

Thanks for your work so far and any assistance that you can provide.

**Comment by cslashm** [comment]
Blue is not supported for now. Sorry.

**Comment by franksanders** [comment]
Any plans for future support or should I plan on buying a nano?
