### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Miner27481** [LedgerHQ/blue-app-monero#3]
Is it possible to install this app at the moment on my Ledger Nano S?

**Comment by stevesbrain** [comment]
You could probably compile a test version and install, however, it is not in a stable/release state yet, so you'd only want to send testnet to it.

**Comment by schadom** [comment]
I'm currently unable to compile the app within the docker env for nano s target. Maybe any hints?

	root@fc2ff9522111:/home/blue-app-monero# make BOLOS_ENV=/opt/ledger-blue/ BOLOS_SDK=/home/nanos-secure-sdk
	TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100002
	Prepare directories
	[DEP]  dep/usbd_ioreq.d
	[DEP]  dep/usbd_hid_impl.d
	[DEP]  dep/usbd_hid.d
	[DEP]  dep/usbd_ctlreq.d
	[DEP]  dep/usbd_core.d
	[DEP]  dep/usbd_conf.d
	[DEP]  dep/usbd_ccid_impl.d
	[DEP]  dep/usbd_ccid_if.d
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:29:
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/usbd_ccid_if.h:173:
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/usbd_ccid_core.h:32:
	/home/nanos-secure-sdk/include/os.h:425:9: warning: 'MIN' macro redefined [-Wmacro-redefined]
	#define MIN(x, y) ((x) < (y) ? (x) : (y))
	        ^
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Core/Inc/usbd_def.h:294:9: note: previous definition is here
	#define MIN(a, b)  (((a) < (b)) ? (a) : (b))
	        ^
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:29:
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/usbd_ccid_if.h:173:
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/usbd_ccid_core.h:32:
	/home/nanos-secure-sdk/include/os.h:426:9: warning: 'MAX' macro redefined [-Wmacro-redefined]
	#define MAX(x, y) ((x) > (y) ? (x) : (y))
	        ^
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Core/Inc/usbd_def.h:297:9: note: previous definition is here
	#define MAX(a, b)  (((a) > (b)) ? (a) : (b))
	        ^
	2 warnings generated.
	[DEP]  dep/usbd_ccid_core.d
	[DEP]  dep/usbd_ccid_cmd.d
	[DEP]  dep/syscalls.d
	[DEP]  dep/pic_internal.d
	[DEP]  dep/pic.d
	[DEP]  dep/os_printf.d
	[DEP]  dep/os_io_seproxyhal.d
	[DEP]  dep/os.d
	[DEP]  dep/monero_ux_nanos.d
	[DEP]  dep/monero_ux_msg.d
	[DEP]  dep/monero_stealth.d
	[DEP]  dep/monero_ram.d
	[DEP]  dep/monero_prehash.d
	[DEP]  dep/monero_outputs.d
	[DEP]  dep/monero_open_tx.d
	[DEP]  dep/monero_nvram.d
	[DEP]  dep/monero_monero.d
	[DEP]  dep/monero_mlsag.d
	[DEP]  dep/monero_main.d
	[DEP]  dep/monero_key.d
	[DEP]  dep/monero_io.d
	[DEP]  dep/monero_inputs.d
	[DEP]  dep/monero_init.d
	[DEP]  dep/monero_dispatch.d
	[DEP]  dep/monero_derivation.d
	[DEP]  dep/monero_crypto.d
	[DEP]  dep/monero_blind.d
	[DEP]  dep/glyphs.d
	TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100002
	[CC]	  obj/glyphs.o
	[CC]	  obj/monero_blind.o
	[CC]	  obj/monero_crypto.o
	[CC]	  obj/monero_derivation.o
	[CC]	  obj/monero_dispatch.o
	[CC]	  obj/monero_init.o
	[CC]	  obj/monero_inputs.o
	[CC]	  obj/monero_io.o
	[CC]	  obj/monero_key.o
	[CC]	  obj/monero_main.o
	src/monero_main.c:168:9: warning: implicit declaration of function 'USB_CCID_power' is invalid in C99
	      [-Wimplicit-function-declaration]
	        USB_CCID_power(1);
	        ^
	src/monero_main.c:169:9: warning: implicit declaration of function 'io_usb_ccid_set_card_inserted' is invalid in C99
	      [-Wimplicit-function-declaration]
	        io_usb_ccid_set_card_inserted(1);
	        ^
	2 warnings generated.
	[CC]	  obj/monero_mlsag.o
	[CC]	  obj/monero_monero.o
	[CC]	  obj/monero_nvram.o
	[CC]	  obj/monero_open_tx.o
	[CC]	  obj/monero_outputs.o
	[CC]	  obj/monero_prehash.o
	[CC]	  obj/monero_ram.o
	[CC]	  obj/monero_stealth.o
	[CC]	  obj/monero_ux_msg.o
	[CC]	  obj/monero_ux_nanos.o
	src/monero_ux_nanos.c:48:3: warning: implicit declaration of function 'io_usb_ccid_set_card_inserted' is invalid in C99
	      [-Wimplicit-function-declaration]
	  io_usb_ccid_set_card_inserted(0);
	  ^
	1 warning generated.
	[CC]	  obj/os.o
	/home/nanos-secure-sdk/src/os.c:310:3: warning: implicit declaration of function 'PRINTF' is invalid in C99
	      [-Wimplicit-function-declaration]
	  PRINTF("%c%07X",0xEE, lr);
	  ^
	1 warning generated.
	[CC]	  obj/os_io_seproxyhal.o
	[CC]	  obj/os_printf.o
	[CC]	  obj/pic.o
	[CC]	  obj/pic_internal.o
	[CC]	  obj/syscalls.o
	[CC]	  obj/usbd_ccid_cmd.o
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_cmd.c:900:12: warning: unused variable
	      'length' [-Wunused-variable]
	  uint16_t length = CCID_RESPONSE_HEADER_SIZE;
	           ^
	1 warning generated.
	[CC]	  obj/usbd_ccid_core.o
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_core.c:123:12: warning: unused variable
	      'len' [-Wunused-variable]
	  uint16_t len;
	           ^
	1 warning generated.
	[CC]	  obj/usbd_ccid_if.o
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:29:
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/usbd_ccid_if.h:173:
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/usbd_ccid_core.h:32:
	/home/nanos-secure-sdk/include/os.h:425:9: warning: 'MIN' macro redefined [-Wmacro-redefined]
	#define MIN(x, y) ((x) < (y) ? (x) : (y))
	        ^
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Core/Inc/usbd_def.h:294:9: note: previous definition is here
	#define MIN(a, b)  (((a) < (b)) ? (a) : (b))
	        ^
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:29:
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/usbd_ccid_if.h:173:
	In file included from /home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/usbd_ccid_core.h:32:
	/home/nanos-secure-sdk/include/os.h:426:9: warning: 'MAX' macro redefined [-Wmacro-redefined]
	#define MAX(x, y) ((x) > (y) ? (x) : (y))
	        ^
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Core/Inc/usbd_def.h:297:9: note: previous definition is here
	#define MAX(a, b)  (((a) > (b)) ? (a) : (b))
	        ^
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:64:10: warning: passing
	      'volatile uint8_t *' (aka 'volatile unsigned char *') to parameter of type 'void *' discards qualifiers
	      [-Wincompatible-pointer-types-discards-qualifiers]
	  memset(&PrevXferComplete_IntrIn, 0, sizeof(PrevXferComplete_IntrIn));
	         ^~~~~~~~~~~~~~~~~~~~~~~~
	/usr/include/string.h:66:28: note: passing argument to parameter '__s' here
	extern void *memset (void *__s, int __c, size_t __n) __THROW __nonnull ((1));
	                           ^
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:486:1: warning: control reaches end
	      of non-void function [-Wreturn-type]
	}
	^
	4 warnings generated.
	[CC]	  obj/usbd_ccid_impl.o
	[CC]	  obj/usbd_conf.o
	[CC]	  obj/usbd_core.o
	[CC]	  obj/usbd_ctlreq.o
	[CC]	  obj/usbd_hid.o
	[CC]	  obj/usbd_hid_impl.o
	[CC]	  obj/usbd_ioreq.o
	[LINK] bin/app.elf
	obj/monero_main.o: In function `main':
	/home/blue-app-monero/src/monero_main.c:169: undefined reference to `io_usb_ccid_set_card_inserted'
	obj/monero_ux_nanos.o: In function `ui_CCID_reset':
	/home/blue-app-monero/src/monero_ux_nanos.c:48: undefined reference to `io_usb_ccid_set_card_inserted'
	/home/blue-app-monero/src/monero_ux_nanos.c:49: undefined reference to `io_usb_ccid_set_card_inserted'
	obj/os.o: In function `os_memset':
	/home/nanos-secure-sdk/src/os.c:270: undefined reference to `__aeabi_memclr'
	/home/nanos-secure-sdk/src/os.c:270: undefined reference to `__aeabi_memset'
	/home/nanos-secure-sdk/src/os.c:270: undefined reference to `__aeabi_memclr'
	obj/os_printf.o: In function `snprintf':
	/home/nanos-secure-sdk/src/os_printf.c:1045: undefined reference to `__aeabi_memset'
	obj/usbd_ccid_if.o: In function `CCID_Init':
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:70: undefined reference to `__aeabi_memclr'
	obj/usbd_ccid_if.o: In function `CCID_BulkMessage_Out':
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:189: undefined reference to `__aeabi_memmove'
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:247: undefined reference to `__aeabi_memmove'
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:240: undefined reference to `__aeabi_memmove'
	obj/usbd_ccid_if.o: In function `SC_XferBlock':
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:516: undefined reference to `__aeabi_memmove'
	obj/usbd_ccid_if.o: In function `io_usb_ccid_reply':
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c:530: undefined reference to `__aeabi_memmove'
	obj/usbd_core.o: In function `USBD_Init':
	/home/nanos-secure-sdk/lib_stusb/STM32_USB_Device_Library/Core/Src/usbd_core.c:66: undefined reference to `__aeabi_memclr4'
	collect2: error: ld returned 1 exit status
	make: *** [bin/app.elf] Error 1

**Comment by aminorex** [comment]
It seems the link command must be missing libc?

**Comment by schadom** [comment]
> It seems the link command must be missing libc?
Ops my bad. Worked out, thanks.

**Comment by cslashm** [comment]
Beta2 available
