### ISSUE TITLE
Feature request: offload scanning to client

### ISSUE THREAD

**Issue by luigi1111** [LedgerHQ/blue-app-monero#7]
Please consider an additional mode where the viewkey is offloaded to the client, and scanning (and subaddress creation) can take place off device. This should be a rather significant improvement in scanning performance.

The downside of course is privacy is entrusted to the client.

**Comment by cslashm** [comment]
Done in Beta2

View key is exported on application start if user agree.

In incoming TX is identified without device help. Then identified Incoming TX are still decoded by device.
